version: '3'

silent: true

vars:
  GO_MODULE: github.com/Slava02/ChatSupport
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.62.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches"

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.13.5
    mvdan.cc/gofumpt@v0.7.0

tasks:
  default:
    cmds:
    - task: tidy
    - task: fmt
    - task: lint
    - task: tests
    - task: build

  tidy:
    cmds:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    cmds:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    cmds:
    - echo "- Format"
    - docker run --rm -v "$(pwd):/app" -w /app tools-image gofumpt -w {{.GO_FILES}}
    - docker run --rm -v "$(pwd):/app" -w /app tools-image gci write -s standard -s default -s "prefix({{.GO_MODULE}})" --skip-generated {{.GO_FILES}}

  lint:
    cmds:
    - echo "- Lint"
    - mkdir -p {{.GOLANGCI_LINT_CACHE}}
    - task: lint:cmd
      vars: {CLI_ARGS: "run -v --fix --timeout=5m ./..."}

  lint:cmd:
    cmds:
    - |
      docker run --rm \
        -v "$(pwd):/app" -w /app \
        -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
        tools-image \
        golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
    - echo "- Tests"
    - go test -race ./...

  build:
    cmds:
    - echo "- Build"
    - go build ./cmd/chat-service

  dev-tools:install:
    cmds:
    - echo "- Build tools Docker image"
    - docker build -t tools-image -f tools.Dockerfile .

  generate:
    cmds:
    - echo "Run go generate..."
    - go generate ./...