[global]
env = "dev"

[log]
level = "debug"

[servers]
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"
[servers.debug]
addr = ":8079"

[sentry]
dsn = ""
